[tool.djlint]
profile = "django"
indent = 4
max_line_length = 120
format_css = true
format_js = true
ignore = "H006,H030,H031"
exclude = ".venv,venv,node_modules,staticfiles"

[tool.djlint.css]
indent_size = 4

[tool.djlint.js]
indent_size = 4
